# Generated by Django 5.1.1 on 2024-10-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'BaseStations',
            },
        ),
    ]
