# Generated by Django 5.1.4 on 2024-12-10 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('sla', models.CharField(max_length=20)),
                ('datetime_open', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_close', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('subscriber', models.CharField(max_length=13)),
                ('comment', models.TextField()),
                ('decide', models.TextField()),
                ('status', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'accident_accident',
                'managed': False,
            },
        ),
    ]
