# Generated by Django 5.1.1 on 2024-11-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=30)),
                ('home', models.CharField(max_length=7)),
                ('entrance', models.IntegerField()),
                ('ind', models.IntegerField()),
                ('stand', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Key_s',
            },
        ),
    ]
