# Generated by Django 5.1.1 on 2024-11-27 11:23

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gazprom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=14)),
                ('number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=255)),
                ('comment', tinymce.models.HTMLField()),
                ('geo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Gazproms',
            },
        ),
    ]
